[program:zoria-telegram-pi]
command=bash -c 'cd /home/workspace/Projects/zoria-telegram-pi && exec npm run start'
directory=/home/workspace/Projects/zoria-telegram-pi
environment=HOME="/root"
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
startretries=20
startsecs=5
stdout_logfile=/dev/shm/zoria-telegram-pi.log
stderr_logfile=/dev/shm/zoria-telegram-pi_err.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
killasgroup=true
stopwaitsecs=4
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3
